"""Ontology persistence backend protocol."""

from __future__ import annotations

from typing import Any, Optional, Protocol

from src.ontology.schema import Entity, EntityType, Relationship, RelationshipType


class OntologyBackend(Protocol):
    """Storage and graph operations used by OntologyStore."""

    def add_entity(self, entity: Entity) -> str: ...
    def get_entity(self, entity_id: str) -> Optional[Entity]: ...
    def get_entity_by_name(self, name: str) -> Optional[Entity]: ...
    def remove_entity(self, entity_id: str) -> bool: ...

    def add_relationship(self, relationship: Relationship) -> str: ...
    def get_relationship(self, rel_id: str) -> Optional[Relationship]: ...

    def query_by_type(self, entity_type: EntityType) -> list[Entity]: ...
    def query_by_attribute(self, key: str, value: Any) -> list[Entity]: ...
    def search(self, query: str) -> list[Entity]: ...
    def add_alias(self, entity_id: str, alias: str, **metadata: Any) -> None: ...
    def aliases_for(self, entity_id: str) -> list[str]: ...
    def search_entity_candidates(
        self,
        query: str,
        entity_types: Optional[list[str]] = None,
        limit: int = 20,
    ) -> list[dict[str, Any]]: ...
    def record_mention(self, payload: dict[str, Any]) -> int: ...
    def enqueue_linking_review(
        self, mention_id: int, candidates: list[dict[str, Any]]
    ) -> int: ...
    def list_linking_reviews(self, status: str = "pending") -> list[dict[str, Any]]: ...
    def resolve_linking_review(
        self, review_id: int, status: str, entity_id: Optional[str], notes: str = ""
    ) -> None: ...
    def add_assertion(self, payload: dict[str, Any]) -> int: ...

    def get_neighbors(
        self,
        entity_id: str,
        relationship_type: Optional[RelationshipType] = None,
        direction: str = "both",
    ) -> list[tuple[Entity, Relationship]]: ...

    def traverse(
        self,
        entity_id: str,
        hops: int = 2,
        relationship_type: Optional[RelationshipType] = None,
    ) -> dict[str, Any]: ...

    def find_path(
        self, source_id: str, target_id: str, max_hops: int = 5
    ) -> Optional[list[str]]: ...

    def get_dependency_chains(
        self,
        entity_id: str,
        rel_types: Optional[list[RelationshipType]] = None,
        max_depth: int = 5,
    ) -> list[list[str]]: ...

    def calculate_exposure_score(
        self, entity_id: str, threat_ids: Optional[list[str]] = None
    ) -> float: ...

    def to_dict(self) -> dict[str, Any]: ...
    def load_dict(self, data: dict[str, Any]) -> None: ...

    @property
    def entity_count(self) -> int: ...

    @property
    def relationship_count(self) -> int: ...

    def all_entities(self) -> list[Entity]: ...
    def all_relationships(self) -> list[Relationship]: ...
